---
title: siteleaf-scaffold
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
exclude:
- README.md
- ".gitignore"
- node_modules/
- bower_components/
- package.json
- npm-debug.log
- webpack.config.js
assets:
  autoprefixer:
    browsers:
    - last 2 versions
    - IE > 9
  compress:
    css: default
    js: default
  autowrite: true
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true
  assets:
  - bundle.js
  sources:
  - _assets/images
  - _assets/js/dist
  - _assets/styles
  - _assets/fonts
gems:
- jekyll-sitemap
- jekyll-assets
- autoprefixer-rails
