---
title: siteleaf-scaffold
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
exclude:
- README.md
- ".gitignore"
- node_modules/
- bower_components/
- package.json
- npm-debug.log
- Gemfile
- Gemfile.lock
- webpack.config.js
assets:
  autoprefixer:
    browsers:
    - last 2 versions
    - IE > 9
  compress:
    css: default
    js: default
  autowrite: true
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  digest: true
  assets:
  - bundle.js
  sources:
<<<<<<< HEAD
    - _assets/images
    - _assets/js/dist
    - _assets/styles
    - _assets/fonts

  #features:
  #  liquid: true | false | default: false
  #  integrity: true | false | default: false
  #  automatic_img_size: true | false | n(fixnum): 2,4,6,8 | default: true
  #  automatic_img_alt : true | false | default: true
gems:
- jekyll-sitemap
- jekyll-assets
- autoprefixer-rails
=======
  - _assets/images
  - _assets/js/dist
  - _assets/styles
  - _assets/fonts
>>>>>>> 2d5b30afb95ab9cf7fdad14826108f1a912c1294
